name: NodeJS GCP app engine deploy

on:
    push:
        branches:
            - main

jobs:
    deployment:
        name: Deploy Github Page
        runs-on: ubuntu-latest
        steps:
            - run: npm run deploy
