name: NodeJS GCP app engine deploy

on:
    push:
        branches:
            - main

jobs:
    setup-build-deploy:
        name: Deploy Github Page
        runs-on: ubuntu-latest
        run: |
            npm run deploy
